import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "../styles.css";
import { ThemeProvider } from "@strapi-portfolio/web/settings";
import { Footer, Header } from "@strapi-portfolio/web/components";
import { PropsWithChildren } from "react";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@strapi-portfolio/web/i18n/routing";
import { notFound } from "next/navigation";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = PropsWithChildren<{
  params: Promise<{ locale: string }>;
}>;

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className}`}>
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
